service: get-user-info

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  vpc:
    securityGroupIds:
      - sg-01196cf96a9df8cf4     # RDS security group
    subnetIds:
      - subnet-0c72b548ad7f3fc68
      - subnet-0c8f92f53358d3853
      - subnet-0f7bee6df88fd4b4e

functions:
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: user
          method: get
          cors: true

plugins:
  - serverless-offline
